
package com.bcj.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "demosoap", targetNamespace = "http://service.soap.bcj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Demosoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testing", targetNamespace = "http://service.soap.bcj.com/", className = "com.bcj.soap.Testing")
    @ResponseWrapper(localName = "testingResponse", targetNamespace = "http://service.soap.bcj.com/", className = "com.bcj.soap.TestingResponse")
    public String testing(
        @WebParam(name = "arg0", targetNamespace = "")
        Address arg0);

}
