
package com.bcj.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "demosoap", targetNamespace = "http://service.soap.bcj.com/", wsdlLocation = "http://localhost:8080/SoapBasic/services/SoapServiceImplementation?wsdl")
public class Demosoap_Service
    extends Service
{

    private final static URL DEMOSOAP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bcj.soap.Demosoap_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bcj.soap.Demosoap_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/SoapBasic/services/SoapServiceImplementation?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/SoapBasic/services/SoapServiceImplementation?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DEMOSOAP_WSDL_LOCATION = url;
    }

    public Demosoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Demosoap_Service() {
        super(DEMOSOAP_WSDL_LOCATION, new QName("http://service.soap.bcj.com/", "demosoap"));
    }

    /**
     * 
     * @return
     *     returns Demosoap
     */
    @WebEndpoint(name = "SoapServiceImplementationPort")
    public Demosoap getSoapServiceImplementationPort() {
        return super.getPort(new QName("http://service.soap.bcj.com/", "SoapServiceImplementationPort"), Demosoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Demosoap
     */
    @WebEndpoint(name = "SoapServiceImplementationPort")
    public Demosoap getSoapServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.bcj.com/", "SoapServiceImplementationPort"), Demosoap.class, features);
    }

}
